version: '3.3'
services:
  deploy:
    image: 'ailohq/build-scripts'
    command: rancher:downtime_deploy[${RANCHER_SERVICE_NAME},${RANCHER_ENV},${GO_PIPELINE_LABEL}]
    environment:
      - SERVICE_NAME
      - RANCHER_ACCESS_KEY
      - RANCHER_SECRET_KEY
      - RANCHER_ENV
      - GO_PIPELINE_LABEL
